"""
Curated scholarship database for U.S. college applicants.
Includes external scholarships and federal aid information.
"""

EXTERNAL_SCHOLARSHIPS = [
    {
        "name": "Gates Scholarship",
        "name_zh": "Gates 獎學金",
        "amount": "Full cost of attendance",
        "amount_zh": "全額學費",
        "eligibility": "U.S. citizen/permanent resident, minority student, Pell-eligible, GPA ≥ 3.3",
        "eligibility_zh": "美國公民/永久居民、少數族裔、Pell 資格、GPA ≥ 3.3",
        "deadline": "September 15",
        "url": "https://www.thegatesscholarship.org/",
        "intl_eligible": False,
    },
    {
        "name": "Coca-Cola Scholars Program",
        "name_zh": "可口可樂獎學金",
        "amount": "$20,000",
        "amount_zh": "$20,000",
        "eligibility": "U.S. citizen/resident, high school senior, any GPA",
        "eligibility_zh": "美國公民/居民、高中畢業生",
        "deadline": "October 31",
        "url": "https://www.coca-colascholarsfoundation.org/",
        "intl_eligible": False,
    },
    {
        "name": "Fulbright Foreign Student Program",
        "name_zh": "富布萊特外國學生計畫",
        "amount": "Tuition + living stipend",
        "amount_zh": "學費 + 生活費",
        "eligibility": "International students (non-U.S.), graduate level",
        "eligibility_zh": "非美國籍學生（研究所）",
        "deadline": "Varies by country (typically Feb–Oct)",
        "url": "https://foreign.fulbrightonline.org/",
        "intl_eligible": True,
    },
    {
        "name": "AAUW International Fellowships",
        "name_zh": "AAUW 國際獎學金",
        "amount": "$18,000–$30,000",
        "amount_zh": "$18,000–$30,000",
        "eligibility": "Women who are not U.S. citizens, full-time study at accredited U.S. institution",
        "eligibility_zh": "非美國籍女性，在美國認可大學全職就讀",
        "deadline": "November 15",
        "url": "https://www.aauw.org/resources/programs/fellowships-grants/current-opportunities/international/",
        "intl_eligible": True,
    },
    {
        "name": "Joint Japan/World Bank Graduate Scholarship",
        "name_zh": "日本/世界銀行研究所獎學金",
        "amount": "Full tuition + living allowance",
        "amount_zh": "全額學費 + 生活費",
        "eligibility": "Citizens of World Bank member country (developing), development-related fields",
        "eligibility_zh": "世界銀行成員國（開發中國家）公民，發展相關領域",
        "deadline": "April 30",
        "url": "https://www.worldbank.org/en/programs/scholarships",
        "intl_eligible": True,
    },
    {
        "name": "Hubert H. Humphrey Fellowship",
        "name_zh": "韓福瑞獎學金",
        "amount": "Full scholarship (non-degree)",
        "amount_zh": "全額（非學位）",
        "eligibility": "Mid-career professionals from designated countries, including Taiwan",
        "eligibility_zh": "含台灣在內的指定國家中級職業人士",
        "deadline": "Varies (apply through US Embassy)",
        "url": "https://www.humphreyfellowship.org/",
        "intl_eligible": True,
    },
    {
        "name": "Rotary Peace Fellowships",
        "name_zh": "扶輪社和平獎學金",
        "amount": "Full tuition + stipend",
        "amount_zh": "全額學費 + 生活費",
        "eligibility": "Any nationality, peace/development related fields, work experience required",
        "eligibility_zh": "任何國籍，和平/發展相關領域，需有工作經驗",
        "deadline": "May 31",
        "url": "https://www.rotary.org/en/our-programs/peace-fellowships",
        "intl_eligible": True,
    },
    {
        "name": "Knight-Hennessy Scholars (Stanford)",
        "name_zh": "史丹佛 Knight-Hennessy 獎學金",
        "amount": "Full graduate funding",
        "amount_zh": "全額研究所費用",
        "eligibility": "Any nationality, any Stanford graduate program, bachelor's degree required",
        "eligibility_zh": "任何國籍，史丹佛研究所任何科系",
        "deadline": "October (varies by program)",
        "url": "https://knight-hennessy.stanford.edu/",
        "intl_eligible": True,
    },
    {
        "name": "MIT Fellowships",
        "name_zh": "MIT 獎學金",
        "amount": "Varies (full to partial)",
        "amount_zh": "不等（全額至部分）",
        "eligibility": "Admitted MIT graduate students, merit + need-based",
        "eligibility_zh": "已錄取 MIT 研究生，學術成就 + 財務需求",
        "deadline": "With application",
        "url": "https://gradadmissions.mit.edu/costs-funding/scholarships-fellowships",
        "intl_eligible": True,
    },
    {
        "name": "DAAD Research Grants (German-U.S. Exchange)",
        "name_zh": "DAAD 研究獎學金（德美交流）",
        "amount": "$2,150–$3,150/month",
        "amount_zh": "$2,150–$3,150/月",
        "eligibility": "Graduate/doctoral students, research in Germany or collaborative programs",
        "eligibility_zh": "研究所/博士生，赴德研究或合作計畫",
        "deadline": "November 15",
        "url": "https://www.daad.org/en/",
        "intl_eligible": True,
    },
    {
        "name": "QuestBridge National College Match",
        "name_zh": "QuestBridge 全國大學配對獎學金",
        "amount": "Full 4-year scholarship",
        "amount_zh": "四年全額獎學金",
        "eligibility": "U.S. citizen/resident, high-achieving low-income high school senior",
        "eligibility_zh": "美國公民/居民、成績優異的低收入高中畢業生",
        "deadline": "September 26",
        "url": "https://www.questbridge.org/",
        "intl_eligible": False,
    },
    {
        "name": "Davis-Putter Scholarship Fund",
        "name_zh": "Davis-Putter 獎學金",
        "amount": "Up to $15,000",
        "amount_zh": "最高 $15,000",
        "eligibility": "U.S.-based student, social justice activism, financial need",
        "eligibility_zh": "在美就讀、社會正義行動主義、財務需求",
        "deadline": "April 1",
        "url": "https://www.davisputter.org/",
        "intl_eligible": True,
    },
]

LOAN_TYPES = [
    {
        "type": "Subsidized Loan",
        "type_zh": "補貼式助學貸款",
        "max_annual": "$3,500–$5,500 (undergrad)",
        "rate_2024": "6.53%",
        "interest_during_school": "Government pays",
        "interest_during_school_zh": "政府負擔",
        "repayment_starts": "6 months after graduation",
        "repayment_starts_zh": "畢業後 6 個月",
        "need_based": True,
        "note": "Best option — no interest accumulation while in school.",
        "note_zh": "最優選項——在校期間無利息累積。",
    },
    {
        "type": "Unsubsidized Loan",
        "type_zh": "非補貼式助學貸款",
        "max_annual": "$5,500–$20,500 (varies by year/status)",
        "rate_2024": "6.53% (UG) / 8.08% (Grad)",
        "interest_during_school": "Accrues immediately",
        "interest_during_school_zh": "立即累積",
        "repayment_starts": "6 months after graduation",
        "repayment_starts_zh": "畢業後 6 個月",
        "need_based": False,
        "note": "Available to all enrolled students regardless of income.",
        "note_zh": "所有在學學生均可申請，不限收入。",
    },
    {
        "type": "Parent PLUS Loan",
        "type_zh": "家長 PLUS 貸款",
        "max_annual": "Up to cost of attendance",
        "rate_2024": "9.08%",
        "interest_during_school": "Accrues immediately",
        "interest_during_school_zh": "立即累積",
        "repayment_starts": "Immediately (deferral available)",
        "repayment_starts_zh": "立即（可申請延期）",
        "need_based": False,
        "note": "Credit check required. High rate — exhaust other options first.",
        "note_zh": "需信用審查，利率較高，建議先用盡其他選項。",
    },
    {
        "type": "Grad PLUS Loan",
        "type_zh": "研究生 PLUS 貸款",
        "max_annual": "Up to cost of attendance",
        "rate_2024": "9.08%",
        "interest_during_school": "Accrues immediately",
        "interest_during_school_zh": "立即累積",
        "repayment_starts": "6 months after graduation",
        "repayment_starts_zh": "畢業後 6 個月",
        "need_based": False,
        "note": "For graduate/professional students. Credit check required.",
        "note_zh": "適用研究所學生，需信用審查。",
    },
    {
        "type": "Private Student Loan",
        "type_zh": "私人助學貸款",
        "max_annual": "Varies by lender",
        "rate_2024": "4%–16% (variable/fixed)",
        "interest_during_school": "Varies by lender",
        "interest_during_school_zh": "依貸款機構而異",
        "repayment_starts": "Varies",
        "repayment_starts_zh": "依合約",
        "need_based": False,
        "note": "Last resort. Higher rates, fewer protections than federal loans.",
        "note_zh": "最後手段。利率較高，保護比聯邦貸款少。",
    },
]
